name: PR action
description: Custom GitHub actions for pull-request or issue in TypeScript
# author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'message-circle'
  color: 'blue'

# Define your inputs here.
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description:
      'The full name of the repository in which to create or update a comment.'
    default: ${{ github.repository }}
  issue-number:
    description:
      'The number of the issue or pull request in which to create a comment.'
  body:
    description: Body of the comment to be posted
    required: true
    default: 'Hello from GitHub action.yml'
  body-path:
    description:
      'The path to a file containing the comment body. Cannot be used in
      conjunction with `body`.'
  milliseconds:
    description: Milliseconds to wait before running the action
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: The milliseconds time

runs:
  using: node20
  main: dist/index.js
