import * as core from '@actions/core'
import { existsSync, readFileSync } from 'fs'

export type Inputs = {
  token: string
  repository: string
  issueNumber: number
  body: string
  bodyPath: string
  bodyVariable1: string
  bodyVariable2: string
}

export function getInputs(): Inputs {
  return {
    token: core.getInput('token'),
    repository: core.getInput('repository'),
    issueNumber: Number(core.getInput('issue-number')),
    body: core.getInput('body'),
    bodyPath: core.getInput('body-path'),
    bodyVariable1: core.getInput('body-variable-1'),
    bodyVariable2: core.getInput('body-variable-2')
  }
}

export function getBody(inputs: Inputs) {
  let body: string = inputs.body

  if (!body && inputs.bodyPath) {
    if (existsSync(inputs.bodyPath)) {
      body = readFileSync(inputs.bodyPath, 'utf-8')
      if (inputs.bodyVariable1) {
        body = body.replace(/{{bodyVariable1}}/g, inputs.bodyVariable1)
      }
      if (inputs.bodyVariable2) {
        body = body.replace(/{{bodyVariable2}}/g, inputs.bodyVariable2)
      } else {
        const bodyVariable2 = 'bodyVariable2 will be generated by API (from TS)'
        body = body.replace(/{{bodyVariable2}}/g, bodyVariable2)
      }
    } else {
      core.warning(`File not found: ${inputs.bodyPath}`)
    }
  }

  return body
}

export function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error)
}
